name = "xcomposer"
compatibility_date = "2026-05-03"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[vars]
BETTER_AUTH_URL = "https://xcomposer.pages.dev"

[[d1_databases]]
binding = "DB"
database_name = "xcomposer"
database_id = "4f75e953-549a-4d95-9834-eaae5152867e"
migrations_dir = "db/migrations"
