name = "xcomposer"
compatibility_date = "2026-05-03"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "xcomposer"
database_id = "0a2ddf6c-30f7-4a97-af22-c6d3d9c0661b"
migrations_dir = "db/migrations"
