import { createApp } from "vue"
import { createPinia } from "pinia"
import App from "@/App.vue"
import router from "@/router"
import "@/style.css"
import "@material/web/button/filled-button.js"
import "@material/web/button/filled-tonal-button.js"
import "@material/web/button/outlined-button.js"
import "@material/web/button/text-button.js"
import "@material/web/dialog/dialog.js"
import "@material/web/iconbutton/filled-tonal-icon-button.js"
import "@material/web/iconbutton/outlined-icon-button.js"
import "@material/web/menu/menu.js"
import "@material/web/menu/menu-item.js"
import "@material/web/progress/circular-progress.js"
import "@material/web/select/outlined-select.js"
import "@material/web/select/select-option.js"
import "@material/web/textfield/outlined-text-field.js"

createApp(App).use(createPinia()).use(router).mount("#app")
